BOOTLOADER = caterina

WPM_ENABLE 			= yes
LTO_ENABLED 		= yes
VIA_ENABLE 			= yes  
MOUSEKEY_ENABLE 	= no

### OLED CONFIG
OLED_ENABLE 		= yes
# OLED_DRIVER 		= SSD1306
# OLED_DRIVER 		= SH1107
# OLED_TRANSPORT 		= i2c

### RGB CONFIG
RGBLIGHT_ENABLE 	= no
RGB_MATRIX_ENABLE 	= yes