BOOTLOADER = caterina

WPM_ENABLE 			= yes

### OPTIMIZATION OPTIONS
MOUSEKEY_ENABLE 	= no
# LTO_ENABLED 		= yes

### OLED CONFIG
OLED_ENABLE 		= yes

### RGB CONFIG
RGBLIGHT_ENABLE 	= yes
VELOCIKEY_ENABLE 	= yes
RGB_MATRIX_ENABLE 	= no