BOOTLOADER = caterina

### OLED CONFIG
OLED_ENABLE = yes
# OLED_DRIVER = SSD1306
OLED_DRIVER = SH1107
# OLED_TRANSPORT = i2c
WPM_ENABLE = yes
LTO_ENABLED = yes

### RGB CONFIG
RGBLIGHT_ENABLE    = yes
RGB_MATRIX_ENABLE  = yes